### ISSUE TITLE
[PLAYBACK] Playback ramdomly gets stuck

### ISSUE THREAD

**Issue by pgilfernandez** [olive-editor/olive#1432]
**Commit Hash** 
7dd9115e

**Platform** 
macOS 10.14.6

**Summary**
Sometimes hitting the play button in "Sequence viewer" or pressing spacebar does not work, it's like playback gets stuck. It happens randomly, I have been experimenting this issue since first v0.2 alpha was made public but I still have not found a pattern.

I have the feeling like it has to do with cache but I'm not sure:

- it usually gets "stuck" when trying to play and the cache is working in the timeline.
- closing and reopening Olive doesn't help but when deleting the cache from Preferences menu seems to "unstuck" it and (not always) solves the problem and then, playback works again correctly.

**Additional Information / Output**
Sometimes I get this log output but I'm not sure it's related with this issue:

[WARNING] Trying to use locale "en_US" but couldn't find a translation for it ((null):0)
[DEBUG] Extracting default OCIO config to "/Users/pablo/Library/Caches/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.15.1 ((null):0)
[INFO] Setting output audio device to "Built-in Output" ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x10bca2000] Warning: data is not aligned! This can lead to a speed loss
[INFO] Setting output audio device to "Built-in Output" ((null):0)
[DEBUG] Removing an empty arena ((null):0)

**Comment by Simran-B** [comment]
> deleting the cache from Preferences menu seems to "unstuck" it and (not always) solves the problem

Deleting the cache via the preferences doesn't delete the entire cache folder, only the frames the cache knows about. If it "lost memory" about some frames for whatever reason (usually a crash), then it could still be an issue with the cache because of not deleted frames.

Can you try to close Olive, delete the entire cache folder manually and start it again? If that always unstucks the playback then it's likely the cached files.

**Comment by pgilfernandez** [comment]
I have tried deleting the entire cache folder and playback worked again when opening Olive.
This time I saved the logs, the one where I got the playback stuck:

[WARNING] Playback queue failed to keep up ((null):0)
objc[12180]: Class FIFinderSyncExtensionHost is implemented in both /System/Library/PrivateFrameworks/FinderKit.framework/Versions/A/FinderKit (0x7fff96a7c3d8) and /System/Library/PrivateFrameworks/FileProvider.framework/OverrideBundles/FinderSyncCollaborationFileProviderOverride.bundle/Contents/MacOS/FinderSyncCollaborationFileProviderOverride (0x117721f50). One of the two will be used. Which one is undefined.
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x116845000] Warning: data is not aligned! This can lead to a speed loss
[DEBUG] Removing an empty arena ((null):0)

And the log when reopening Olive without deleting the cache folder and the playback still stuck:

[WARNING] Trying to use locale "en_US" but couldn't find a translation for it ((null):0)
[DEBUG] Extracting default OCIO config to "/Users/pablo/Library/Caches/olivevideoeditor.org/Olive/ocioconf" ((null):0)
[INFO] Using Qt version: 5.15.1 ((null):0)
[INFO] Setting output audio device to "Built-in Output" ((null):0)
[INFO] Setting output audio device to "Built-in Output" ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x10ced2000] Warning: data is not aligned! This can lead to a speed loss
[DEBUG] Removing an empty arena ((null):0)

**Comment by itsmattkc** [comment]
I've run into this too but haven't had a moment to debug it. I'll try to soon.

**Comment by itsmattkc** [comment]
This should be fixed as of the recent merge from `nodearchchanges`. Can you confirm?

**Comment by pgilfernandez** [comment]
As on today´s last build, 2d420dec, it still happens to me...
Anything else to try?

**Comment by itsmattkc** [comment]
Any improvement with 9b49bea0967f3704b3a9c7ece5d52b6a9e6604fe ?

**Comment by pgilfernandez** [comment]
I'm sorry to say that it still gets stuck in f99600ed... as often as before.

**Comment by itsmattkc** [comment]
Can you provide a video of this behavior?

**Comment by itsmattkc** [comment]
Is this fixed in fcb344bd4ed2cfa0c69c758de07ba91d5da9ae0a?

**Comment by pgilfernandez** [comment]
To tell you the truth, I've been trying daily the new builds but none of them have solved this issue #1522 and transform node can't transform title clips so I couldn't play with enough "tools" to test this one again. Anyway, I would say it's more stable every day and it stuck less than before.
Today, with 573597be it also stuck once but it was because of that "transform node that can't transform title clips", once I deleted it and restored the connection of the text node to the text clip, the playback worked back again.

I will continue trying and let you know.

**Comment by itsmattkc** [comment]
I wasn't aware of transform node/title node issues, is that fixed now in 67f48bc37c8348f919d5b631f1bf04818eea1ba6?

Can you please provide a screen recording of this issue occurring? Otherwise I'm just shooting in the dark.

**Comment by pgilfernandez** [comment]
Nice, the transform node/title node issue is fixed.

Let me play a little bit more in order to try to get "the playback stuck" again... now I couldn't stuck it.

**Comment by pgilfernandez** [comment]
I would say you can close this issue, it didn't stuck in a long while for me... =D
