### ISSUE TITLE
[CRASH] 

### ISSUE THREAD

**Issue by dag-odoo** [olive-editor/olive#1539]
**Commit Hash** 

**Platform** mac Os 10.15

**Summary**
Olive crashes when I dock the scope waveform window on top of the timeline

**Steps to Reproduce**

1. Import 1080p footage, 24fps
2. double click to preview
3. In preview window, right click, scopes -> waveform -> A window appears
4. Dock waveform window -> crash

<details><summary><strong>Backtrace</strong></summary><pre><code>

[WARNING] Failed to set name of parameter "track_in_0" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to set name of parameter "track_in_1" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to set name of parameter "track_in_2" in node "org.olivevideoeditor.Olive.vieweroutput" - input doesn't exist ((null):0)
[WARNING] Failed to get data type of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get standard value of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get data type of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)

[WARNING] Failed to get standard value of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get data type of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get standard value of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get data type of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get standard value of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get data type of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get standard value of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get data type of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[WARNING] Failed to get standard value of parameter "" in node "org.olivevideoeditor.Olive.footage" - input doesn't exist ((null):0)
[DEBUG] No arenas, creating new... ((null):0)
[swscaler @ 0x10e220800] Warning: data is not aligned! This can lead to a speed loss
Process 921 stopped
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=EXC_I386_GPFLT)
    frame #0: 0x00000001000f0818 Olive`olive::OpenGLRenderer::CreateNativeTexture2D(int, int, olive::VideoParams::Format, int, void const*, int) + 56
Olive`olive::OpenGLRenderer::CreateNativeTexture2D:
->  0x1000f0818 <+56>: callq  *0xa8(%rax)
    0x1000f081e <+62>: movq   0x28(%rbx), %rax
    0x1000f0822 <+66>: movq   (%rax), %rax
    0x1000f0825 <+69>: movl   $0xcf2, %edi              ; imm = 0xCF2 
Target 0: (Olive) stopped.

</code></pre></details>

**Additional Information**
Mac pro 5.1, 96GB ram, 512 mb VRAM AMD 5870, footage 1080p, 24fps

**Comment by itsmattkc** [comment]
Is this fixed as of abe28f81bf82b76d8e6ae8d5f075c259eb558289?

**Comment by dag-odoo** [comment]
Still crashing with 8f21d05b (when I open the waveform scope window this time).

**Comment by itsmattkc** [comment]
Might be AMD related: #1574

**Comment by Simran-B** [comment]
#1574 is resolved, can you please try again @dag-odoo

**Comment by dag-odoo** [comment]
@Simran-B It works, no more crashes :)
