### ISSUE TITLE
.mp3, .ogg, and .wav import sounds are broken/desynced

### ISSUE THREAD

**Issue by Corruptinator** [olive-editor/olive#359]
Version: [_Jan 2019_ | **1d85c42**] Windows 10 64-Bit

I noticed that after importing .mp3 into a project sequencer there are no waveforms shown on the timeline and does not play back sound. (**Edit**: Same thing for _.ogg_, no sound playback) For .wav, it does play back sound but starts playing the beginning part of the sound regardless of where the playback marker is set on the sequencer timeline. Say I hit stop and stop the music, then moving the timeline marker back at the start and press play, the song/sound still continues where it was left off instead of going back at the beginning. The .WAV files are desynced from the sequencer timeline. Wav files also show flat waveforms in the timeline. (**Edit**: _.M4a_ [AAC] is affected as like the WAV format)

![image](https://user-images.githubusercontent.com/5027750/51649781-aea31b80-1f3a-11e9-90c2-fef42a208f02.png)

Possible sound import regression perhaps?

**Comment by itsmattkc** [comment]
Interesting, this issue appears to be very similar to #313, which I haven't been able to address since I haven't been able to recreate it. Could you send the full debug log when you import these files and provide your computers's specs?

**Comment by itsmattkc** [comment]
Scratch that last statement, I was finally able to recreate. Expect a fix soon.

**Comment by Corruptinator** [comment]
Sorry, my computer ran out of power. Haven't done Debug Log before.

**Comment by pgilfernandez** [comment]
I macOS it happens something similar... but it seems to happen with all sound files:
<img width="1120" alt="captura de pantalla 2019-01-24 a las 8 47 43" src="https://user-images.githubusercontent.com/5942369/51662648-d2a34300-1fb4-11e9-9b39-45527966e5da.png">

**Comment by itsmattkc** [comment]
I believe 32479b1b8395004e06d46e5289b19632fed8a6d5 should fix this, let me know if it does!

**Comment by Corruptinator** [comment]
I redownloaded Olive from the downloads page, didn't show which version number it was, Audio is still desynced and some still can't play normally. I did get the Debug Log though:

```
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[INFO] Found the following audio devices: (:0, )
[DEBUG] "Speakers (4- Sennheiser 3D G4ME1)" (:0, )
[DEBUG] "Speakers (4- Sennheiser 3D G4ME1)" (:0, )
[INFO] Using audio device "Default Output Device" (:0, )
[WARNING] libpng warning: iCCP: known incorrect sRGB profile (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[INFO] Clip opened on track 0 (:0, )
[INFO] Clip closed on track 0 (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[INFO] Clip opened on track 0 (:0, )
[INFO] Auto-recovery project saved (:0, )
[INFO] Clip closed on track 0 (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[INFO] Clip opened on track 0 (:0, )
[INFO] Clip closed on track 0 (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[INFO] Clip opened on track 0 (:0, )
[INFO] Clip closed on track 0 (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[WARNING] Tried to display clip 0 but it's closed (:0, )
[INFO] Clip opened on track 0 (:0, )
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[WARNING] Invalid values passed to get_buffer_offset_from_frame 0 
[INFO] Auto-recovery project saved (:0, )
```

**Comment by itsmattkc** [comment]
Sorry I accidentally uploaded an older build, try it now

**Comment by Corruptinator** [comment]
Hang on... download is slow.

**Comment by Corruptinator** [comment]
Ugh. Download Failed. Network Error. Still trying to download.

**Comment by Corruptinator** [comment]
It works, Waveforms are also shown on the timeline. Thanks!

**Comment by itsmattkc** [comment]
Awesome! really glad to have solved that one :)

**Comment by Corruptinator** [comment]
:)
