### ISSUE TITLE
Image Sequence Importing Fils and Shows Errors in Bin

### ISSUE THREAD

**Issue by brendanhowell** [olive-editor/olive#393]
I am unable to import image sequences. Steps to reproduce:
1. File > Import
2. Select an image file (or multiple) in a folder with other images all with the same size.
3. Click ok when asked if it should be imported as an image sequence.

The import completes but the clip in the bin has an X icon next to it's name. The tooltip indicates "Filename /home/mute/Pictures/dscf%04d.jpg Could not open file."

I am on arch linux:
`Linux octavia 4.20.3-arch1-1-ARCH #1 SMP PREEMPT Wed Jan 16 22:38:58 UTC 2019 x86_64 GNU/Linux`

Debug log:
```
 [INFO] Initializing effects... (:0, )
[INFO] Finished initializing effects (:0, )
[WARNING] QLayout: Attempting to add QLayout "" to DemoNotice "", which already has a layout (:0, )
[WARNING] QObject::connect: No such signal DemoNotice::finished() (:0, )
[WARNING] QFileInfo::absolutePath: Constructed with empty filename (:0, )
[INFO] Auto-recovery project saved (:0, )

```

**Comment by itsmattkc** [comment]
Can you run Olive from command line and see if there's extra debug output from there?

**Comment by brendanhowell** [comment]
Sure. Same steps give this console output:
```
[INFO] Initializing effects... ((null):0, (null))
[INFO] Finished initializing effects ((null):0, (null))
[WARNING] QLayout: Attempting to add QLayout "" to DemoNotice "", which already has a layout ((null):0, (null))
[WARNING] QObject::connect: No such signal DemoNotice::finished() ((null):0, (null))
[image2 @ 0x7f7bd80051e0] Could find no file with path '/home/mute/Pictures/2018-11-01/dscf%04d.jpg' and index in the range 0-4
[WARNING] QFileInfo::absolutePath: Constructed with empty filename ((null):0, (null))
```

**Comment by itsmattkc** [comment]
Any improvement with c9f686819837669f95a3f806afe0275a0deb6fa8?

**Comment by itsmattkc** [comment]
I'll assume this issue is fixed having heard no other reports of it since c9f6868

**Comment by brendanhowell** [comment]
I just got around to testing with the latest build (https://github.com/olive-editor/olive/commit/3233c0d0f96210b973e485911c4bc84103c593ed) and I still have the same problems.

`
2019-02-26T14:08:32 [WARNING] QApplication: invalid style override passed, ignoring it.
2019-02-26T14:08:32 [INFO] Initializing custom cursors
2019-02-26T14:08:32 [INFO] Finished initializing custom cursors
2019-02-26T14:08:32 [INFO] Initializing effects...
2019-02-26T14:08:32 [INFO] Finished initializing effects
[image2 @ 0x7f8bd0004a40] Could find no file with path '/home/mute/Pictures/2018-11-01/dscf%4d.jpg' and index in the range 0-4
2019-02-26T14:08:49 [WARNING] QObject::connect: Cannot queue arguments of type 'QVector<int>'
(Make sure 'QVector<int>' is registered using qRegisterMetaType().)
2019-02-26T14:09:33 [WARNING] QFileInfo::absolutePath: Constructed with empty filename
2019-02-26T14:09:33 [INFO] Auto-recovery project saved
`

I'm using the AppImage, if that makes any difference.

**Comment by itsmattkc** [comment]
This should be completely fixed in 1ae3b877a12fea013e41d559869aa560a41debd8

**Comment by brendanhowell** [comment]
Yaaas! It's fixed for me. Nice work.
