### ISSUE TITLE
Two-finger scrolling in the timeline

### ISSUE THREAD

**Issue by elsandosgrande** [olive-editor/olive#505]
I know this is a minor issue, but I can't scroll when hovering over the timeline. 

Basically, I can use horizontal two-finger scrolling in KDEnlive to easily scroll through the timeline without breaking my flow, but I always have to drop down to the scrollbar before I can use two-finger scrolling, but I might as well drag the bar at that point.

Post Scriptum
It is at this point in typing that I checked and yes, there is scrolling, but it's only vertical (like a mouse-wheel), so my issue stands.

**Comment by itsmattkc** [comment]
You should be able to scroll horizontally too by holding Alt

**Comment by elsandosgrande** [comment]
I'll check, but that is not necessary with KDEnlive (again, I did state that it was probably a minor issue, of course when considering the stage of development and all of the other issues in the backlog).

Post Scriptum
Nope, alt makes it not scroll, even horizontally.

**Comment by itsmattkc** [comment]
Actually disregard my previous message.

Vertical scrolling on the timeline is supposed to scroll horizontally by default. You're saying this doesn't happen? What desktop environment are you using?

**Comment by elsandosgrande** [comment]
I'm not talking about the axis of the timeline, but of my fingers. When I move my two fingers from-left-to-right, it doesn't scroll, but when I move my fingers up-down, it does scroll. 

Antergos KDE by the way.

**Comment by oc1024** [comment]
What at @elsandosgrande wants, I think, is to be able to scroll the timeline horizontally with horizontal two finger scrolling instead of having to make the rather unintuitive association " fingers up and down = timeline left right".

**Comment by elsandosgrande** [comment]
@oc1024 You're my man! It's so much easier in KDEnlive. Also, the scrolling feels like the sensitivity was turned down to a very low preset until I get to the scrollbar (I guess KDE itself takes over then).

**Comment by mdmayfield** [comment]
I kind of expected that too, that two-finger horizontal scrolling would work. In some media applications, vertical scrolling zooms in/out and horizontal scrolling scrolls; personally, my preference would be:

#### "Natural" scrolling
- Two fingers move up on the touchpad: timeline scrolls to show later events
- Two fingers move down on the touchpad: timeline scrolls to show earlier events
- Two fingers move left on the touchpad: timeline scrolls to show later events
- Two fingers move right on the touchpad: timeline scrolls to show earlier events

#### Traditional scrolling
- Two fingers move up on the touchpad: timeline scrolls to show earlier events
- Two fingers move down on the touchpad: timeline scrolls to show later events
- Two fingers move left on the touchpad: timeline scrolls to the show earlier events
- Two fingers move right on the touchpad: timeline scrolls to show later events

**Comment by elsandosgrande** [comment]
@mdmayfield Well, you've got that down to a T. 

Now that all that's left is the implementation, why is my pull being left alone @itsmattkc ? I don't think I can sync my fork with it open, so yeah.

**Comment by naj59** [comment]
@elsandosgrande
[Sure you can](https://gist.github.com/CristinaSolana/1885435]

**Comment by elsandosgrande** [comment]
I meant on the site. You know, [this way](https://stackoverflow.com/questions/7244321/how-do-i-update-a-github-forked-repository) (the second answer from the top, the "switching the base" one). I did it once before the current pull, but I only get "View pull request" now.

**Comment by naj59** [comment]
@elsandosgrande
Just a simple push after pulling the upstream. I do this with every fork on every site (even on Bitbucket).

**Comment by elsandosgrande** [comment]
For me it's just easier to have it automated (git's one thing I don't like to use in the terminal, not that not knowing it helps much in that regard).

Guess I'll just wait for him to approve the merge.

**Comment by naj59** [comment]
@elsandosgrande Sorry to say, but using 'Git' over the website is not recommended and completely *destroys* the flow. It is more a pain. Learn the CLI, its awesome!

**Comment by elsandosgrande** [comment]
Yeah, but from where?

**Comment by naj59** [comment]
@elsandosgrande
https://learnxinyminutes.com/docs/git/

**Comment by elsandosgrande** [comment]
Thanks, though will using git to sync retain all commit data from upstream?

**Comment by itsmattkc** [comment]
I can't test this because I'm not on a platform that supports pixel scrolling, but I wrote a pixel scroll handler according to specification in 65a136b0e99d69577e3613ce939b1ab8c5c3c59b. Let me know if it behaves as expected.

**Comment by elsandosgrande** [comment]
@itsmattkc So, scrolling on the scrollbar has a flipped direction now (traditional instead of natural; when I drag right, the bar moves left and vice versa) and the timeline only goes one way, regardless of the direction of my fingers (it keeps going to the right, even if I'm dragging in the opposite direction/to the left and even when switching directions mid-scroll, like KDEnlive when it glitches out thanks to Movit having a bad day).

**Comment by itsmattkc** [comment]
I'm not sure what that could be I'm afraid (again, I don't have a way of testing this thoroughly at the moment). [Qt documentation](https://doc.qt.io/qt-5/qwheelevent.html#pixelDelta) does indicate that "On X11 this value is driver specific and unreliable". Hopefully it's not just that.

**Comment by elsandosgrande** [comment]
Well, I'm using Wayland, so yeah. Also, it seems that OpenGL and X11 don't mix well, as the only time I could get my X11 session to be even partially usable (become able to record a video with OBS, but nothing practical) was when I switched it XRender, so yeah. To be fair, XWayland shouldn't deviate, so we should be good (it works in KDEnlive, so I'd say that's good enough). 

By the way, I'm using libinput. [pakku -Qi libinput.txt](https://github.com/olive-editor/olive/files/2871419/pakku.-Qi.libinput.txt)

**Comment by oc1024** [comment]
> the timeline only goes one way, regardless of the direction of my fingers

Can confirm.

**Comment by elsandosgrande** [comment]
We seem to share the same experiences. What's your touchpad driver (synaptics or libinput)?

**Comment by oc1024** [comment]
@oc1024 X11 Libinput (Arch Cinnamon)

**Comment by alcomposer** [comment]
For some reason scrolling left is the same as scrolling right? I am on Antergos, libinput, Elantech Touchpad

**Comment by itsmattkc** [comment]
I've disabled the pixel scrolling code for now until I get a chance to test it

**Comment by alcomposer** [comment]
Ok, this is a good idea. However it will be a good feature!

**Comment by elsandosgrande** [comment]
> For some reason scrolling left is the same as scrolling right? I am on Antergos, libinput, Elantech Touchpad

Yeah, that'll need some more testing. Maybe I can work on that once I learn C++.

**Comment by itsmattkc** [comment]
Should be solved with the merge of #564

**Comment by elsandosgrande** [comment]
Yeah, it is still broken the least time I checked, which was less than a month ago.
