### ISSUE TITLE
[Bug] Misaligned media list in folder

### ISSUE THREAD

**Issue by BrimsonBhin** [olive-editor/olive#661]
Sorry for the bug infestation, but this bug was inherited **before** the recent UI separation (`ed05ced`). Visual example found from this [Reddit Post](https://www.reddit.com/r/olive/comments/b284xt/my_experience_with_olive_editor/)

![image](https://user-images.githubusercontent.com/40442071/54736391-1c994700-4b68-11e9-8828-862ec155b512.png)

### System Information

**Olive version:**  ` 1da4a31`
**Source:** GitHub Continuous
**Operating system:** [Windows 10 64-bit]

### Detailed Description

Olive disorganizes content in the folder

### Steps to reproduce

1. Import media in any way possible
2. Organize the media into a folder
3. Save project
3. Restart Olive
4. Strange gaps may appear in the folder's' content

This was happening to me too

**Comment by itsmattkc** [comment]
This should be fixed in 067eec0b90aea3e43c26f972177c21802d369b7f, but let me know if not

**Comment by BrimsonBhin** [comment]
@itsmattkc Fixed, but loading projects with previous folders crashes Olive (#665)

**Comment by itsmattkc** [comment]
The crash should be fixed in d0b7004b8f8e97b3f32a9de6b6191bde77579f31, but it looks like the gaps are not.

**Comment by ngreve** [comment]
I still have this issue.

Olive version: 6264123b (always had this version)
OS: Arch Linux (5.0.7-arch1-1-ARCH)

Furthermore, if I drop a file from the OS file explorer onto one of these gaps, olive crashes with "Segmentation fault (core dumped)".
